// <auto-generated />
using GestionDeContacts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeContacts.Migrations
{
    [DbContext(typeof(ContactAPIContext))]
    partial class ContactAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDeContacts.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tel")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "1 allee de lespoir",
                            Email = "johnny@gmail.com",
                            Nom = "Doe",
                            Prenom = "John",
                            Tel = 523154174L
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "1 allee de la casse",
                            Email = "bebeb@gmail.com",
                            Nom = "Bebeb",
                            Prenom = "Doudou",
                            Tel = 213457823L
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "1 allee de loi",
                            Email = "kojdeb@gmail.com",
                            Nom = "Debian",
                            Prenom = "Koji",
                            Tel = 142762320L
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "1 allee de leojfe",
                            Email = "kod@gmail.com",
                            Nom = "Kilou",
                            Prenom = "Kodoud",
                            Tel = 154235302L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
